version: '3.7'

services:

  web:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - '.:/hackyfeed'
      - '/hackyfeed/node_modules'
    ports:
      - 8080:8080
    environment:
      - CHOKIDAR_USEPOLLING=true
